import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const readProjectFile = (relativePath) => fs.readFileSync(
  new URL(`../../${relativePath}`, import.meta.url),
  'utf8'
)

test('client login uses RPC and does not select password columns directly', () => {
  const useGameState = readProjectFile('src/hooks/useGameState.jsx')
  const supabaseClient = readProjectFile('src/lib/supabase.js')

  assert.match(useGameState, /supabase\.rpc\('login_admin_session'/)
  assert.match(useGameState, /supabase\.rpc\('login_team'/)
  assert.match(useGameState, /adminSessionExpiresAt/)
  assert.match(useGameState, /setSupabaseAdminSessionToken\(adminSessionToken\)/)
  assert.match(useGameState, /adminSessionToken/)
  assert.match(supabaseClient, /ADMIN_SESSION_HEADER = 'x-admin-session-token'/)
  assert.match(supabaseClient, /fetchWithAdminSession/)
  assert.match(supabaseClient, /headers\.set\(ADMIN_SESSION_HEADER, token\)/)
  assert.match(useGameState, /const normalizeEmbeddedMatchTeam = \(team, fallbackId\) =>/)
  assert.match(useGameState, /delete publicTeam\.password/)
  assert.match(useGameState, /\(teamAId \? teamById\[teamAId\] : null\) \|\| normalizeEmbeddedMatchTeam\(m\.teamA, teamAId\)/)
  assert.doesNotMatch(useGameState, /const teamA = m\.teamA \|\|/)
  assert.doesNotMatch(useGameState, /const teamB = m\.teamB \|\|/)
  assert.doesNotMatch(useGameState, /TEAM_LOGIN_COLUMNS/)
  assert.doesNotMatch(useGameState, /\.select\([^)]*password/)
  assert.doesNotMatch(useGameState, /admin_credential[\s\S]{0,120}\.select\('status'\)/)
})

test('client Supabase runtime config rejects localhost and http in production', () => {
  const supabaseClient = readProjectFile('src/lib/supabase.js')

  assert.match(supabaseClient, /const isAllowedLocalHost = !import\.meta\.env\.PROD && isLocalSupabaseHost\(hostname\)/)
  assert.match(supabaseClient, /const hasAllowedProtocol = parsed\.protocol === 'https:' \|\| \(isAllowedLocalHost && parsed\.protocol === 'http:'\)/)
  assert.doesNotMatch(supabaseClient, /\['http:', 'https:'\]\.includes\(parsed\.protocol\)/)
})

test('match result claims require the winner to belong to the active match', () => {
  const useGameState = readProjectFile('src/hooks/useGameState.jsx')
  const sql = readProjectFile('server/supabase_policies.sql')

  assert.match(useGameState, /supabase\.rpc\('declare_match_winner'/)
  assert.match(sql, /create or replace function public\.declare_match_winner/)
  assert.match(sql, /if not public\.valid_admin_session\(\) then/)
  assert.match(sql, /delete from public\.active_matches[\s\S]*p_winner_id in \(team_a, team_b\)[\s\S]*returning \* into match_row/)
  assert.match(sql, /insert into public\.match_history/)
  assert.match(sql, /insert into public\.matchmaking_queue[\s\S]*on conflict \(team_id\) do update/)
})

test('Supabase SQL keeps password hashing, login RPCs, and credential checks in place', () => {
  const sql = readProjectFile('server/supabase_policies.sql')

  assert.match(sql, /create or replace function public\.hash_team_password_before_write/)
  assert.match(sql, /create trigger teams_hash_password_before_write/)
  assert.match(sql, /create or replace function public\.login_team/)
  assert.match(sql, /create table if not exists private\.admin_sessions/)
  assert.match(sql, /revoke all on schema private from public, anon, authenticated/)
  assert.match(sql, /revoke all on all tables in schema private from public, anon, authenticated/)
  assert.match(sql, /create or replace function public\.login_admin_session/)
  assert.match(sql, /create or replace function public\.valid_admin_session/)
  assert.match(sql, /current_setting\('request\.headers', true\)[\s\S]*'x-admin-session-token'/)
  assert.match(sql, /insert into private\.admin_sessions[\s\S]*encode\(extensions\.digest\(session_token, 'sha256'\), 'hex'\)/)
  assert.match(sql, /s\.token_hash = encode\([\s\S]*extensions\.digest\([\s\S]*'sha256'[\s\S]*'hex'[\s\S]*\)/)
  assert.match(sql, /drop function if exists public\.login_admin\(text, text\)/)
  assert.doesNotMatch(sql, /create or replace function public\.login_admin\(/)
  assert.doesNotMatch(sql, /grant execute on function public\.login_admin\(text, text\) to anon, authenticated/)
  assert.match(sql, /create or replace function public\.admin_credential_configured/)
  assert.match(sql, /create or replace function public\.declare_match_winner/)
  assert.match(sql, /grant execute on function public\.declare_match_winner\(uuid, uuid, text\) to anon, authenticated/)
  assert.match(sql, /create or replace function public\.prevent_duplicate_active_match_team[\s\S]*Active match teams must be eligible and have tokens/)
  assert.match(sql, /pg_advisory_xact_lock\(hashtextextended\(least\(new\.team_a::text, new\.team_b::text\), 0\)\)/)
  assert.match(sql, /pg_advisory_xact_lock\(hashtextextended\(greatest\(new\.team_a::text, new\.team_b::text\), 0\)\)/)
  assert.match(sql, /create or replace function public\.sync_active_match_team_status/)
  assert.match(sql, /create trigger active_matches_sync_team_status/)
  assert.match(sql, /create or replace function public\.clear_active_match_queue_rows/)
  assert.match(sql, /create trigger active_matches_clear_queue_rows/)
  assert.match(sql, /matchmaking_queue_no_self_match/)
  assert.match(sql, /update public\.active_matches[\s\S]*"teamA" - 'password'[\s\S]*"teamB" - 'password'/)
  assert.match(sql, /create or replace function public\.strip_active_match_team_snapshots/)
  assert.match(sql, /create trigger active_matches_strip_team_snapshots/)
  assert.match(sql, /create or replace function public\.prevent_active_match_team_runtime_edit/)
  assert.match(sql, /Resolve active match before editing team runtime/)
  assert.match(sql, /create trigger teams_prevent_active_match_runtime_edit/)
  assert.match(sql, /create or replace function public\.prevent_active_match_team_delete/)
  assert.match(sql, /Resolve active match before deleting team/)
  assert.match(sql, /create trigger teams_prevent_active_match_delete/)
  assert.match(sql, /revoke select on table public\.teams from anon, authenticated/)
  assert.match(sql, /grant select \([\s\S]*last_token_update_time[\s\S]*\) on table public\.teams to anon, authenticated/)
  assert.match(sql, /create policy teams_insert on public\.teams[\s\S]*with check \(public\.valid_admin_session\(\)\)/)
  assert.match(sql, /create policy active_matches_delete on public\.active_matches[\s\S]*using \(public\.valid_admin_session\(\)\)/)
  assert.match(sql, /create policy token_history_insert on public\.token_history[\s\S]*with check \(public\.valid_admin_session\(\)\)/)
  assert.match(sql, /create policy system_select on public\.system[\s\S]*using \(key = 'game'\)/)
  assert.match(sql, /create policy system_update on public\.system[\s\S]*with check \(key = 'game' and public\.valid_admin_session\(\)\)/)
  assert.doesNotMatch(sql, /for insert to anon, authenticated\s+with check \(true\)/)
  assert.doesNotMatch(sql, /for update to anon, authenticated\s+using \(true\)\s+with check \(true\)/)
  assert.doesNotMatch(sql, /for delete to anon, authenticated\s+using \(true\)/)
  assert.doesNotMatch(sql, /SET_BASE64_ADMIN_CREDENTIAL/)
})

test('Supabase verifier includes an optional live mutation probe', () => {
  const verifier = readProjectFile('scratch/test_supabase.js')
  const localSqlVerifier = readProjectFile('scripts/verify-supabase-sql-local.js')
  const applyPoliciesScript = readProjectFile('scripts/apply-supabase-policies.js')
  const packageJson = JSON.parse(readProjectFile('package.json'))

  assert.match(verifier, /VERIFY_SUPABASE_MUTATIONS/)
  assert.match(verifier, /redactCliOutput/)
  assert.match(verifier, /safeSupabaseUrlLabel/)
  assert.match(verifier, /<invalid>/)
  assert.match(verifier, /validateSupabaseProductionEnv/)
  assert.match(verifier, /Supabase verification cannot start with invalid config/)
  assert.match(verifier, /formatSupabaseError/)
  assert.match(verifier, /error\?\.message \|\| error\?\.details \|\| error\?\.hint \|\| error\?\.code/)
  assert.match(verifier, /select failed for required columns/)
  assert.doesNotMatch(verifier, /console\.log\('URL:'/)
  assert.doesNotMatch(verifier, /console\.log\('Key length:'/)
  assert.match(verifier, /VERIFY_SUPABASE_ADMIN_USERNAME/)
  assert.match(verifier, /VERIFY_SUPABASE_ADMIN_PASSWORD/)
  assert.match(verifier, /process\.argv\.includes\('--mutations'\)/)
  assert.match(verifier, /login_admin_session/)
  assert.match(verifier, /declare_match_winner/)
  assert.match(verifier, /Admin session login RPC reachable/)
  assert.doesNotMatch(verifier, /supabase\.rpc\('login_admin'/)
  assert.match(verifier, /x-admin-session-token/)
  assert.match(verifier, /mutation probe team login passed/i)
  assert.match(verifier, /const createProbeSuffix = \(\) => `\$\{Date\.now\(\)\.toString\(36\)\}/)
  assert.match(verifier, /verifyAlpha\$\{suffix\}/)
  assert.match(verifier, /verifyBravo\$\{suffix\}/)
  assert.match(verifier, /verifyAnon\$\{suffix\}/)
  assert.match(verifier, /const cleanupTeamNames = \[\.\.\.teamNames, anonTeamName\]/)
  assert.doesNotMatch(verifier, /__verify_alpha_\$\{suffix\}/)
  assert.doesNotMatch(verifier, /__verify_bravo_\$\{suffix\}/)
  assert.doesNotMatch(verifier, /__verify_anon_blocked_\$\{suffix\}/)
  assert.match(verifier, /duplicate active-match guard passed/i)
  assert.match(verifier, /atomic winner declaration passed/i)
  assert.match(verifier, /leaked-alpha-password/)
  assert.match(verifier, /active-match snapshot stripping passed/i)
  assert.match(verifier, /active-match status sync passed/i)
  assert.match(verifier, /active-match queue cleanup passed/i)
  assert.match(verifier, /active-match runtime edit guard passed/i)
  assert.match(verifier, /active-match team delete guard passed/i)
  assert.match(verifier, /Mutation probe cleanup complete/)
  assert.match(localSqlVerifier, /postgres:16-alpine/)
  assert.match(localSqlVerifier, /server\/supabase_policies\.sql/)
  assert.match(localSqlVerifier, /declare_match_winner/)
  assert.match(localSqlVerifier, /duplicate active match guard/)
  assert.match(localSqlVerifier, /active-match team snapshot password stripping/)
  assert.match(localSqlVerifier, /active-match queue cleanup/)
  assert.match(localSqlVerifier, /self matchmaking queue lock guard/)
  assert.match(localSqlVerifier, /verifyAnonymousWriteGuards/)
  assert.match(localSqlVerifier, /anon teams update without admin session/)
  assert.match(localSqlVerifier, /anon matchmaking_queue insert without admin session/)
  assert.match(localSqlVerifier, /anon active_matches delete without admin session/)
  assert.match(localSqlVerifier, /anon system update without admin session/)
  assert.match(localSqlVerifier, /invalid admin-header team insert/)
  assert.match(localSqlVerifier, /phase transition declare_match_winner local check/)
  assert.match(localSqlVerifier, /phase transition history wager flag/)
  assert.equal(packageJson.scripts['verify:supabase:mutations'], 'node scratch/test_supabase.js --mutations')
  assert.equal(packageJson.scripts['verify:supabase:local-sql'], 'node scripts/verify-supabase-sql-local.js')
  assert.equal(packageJson.scripts['verify:event'], 'npm run verify && npm run verify:browser && npm run verify:browser:configured && npm run verify:admin-workflow && npm run verify:supabase:local-sql && npm run verify:supabase:mutations')
  assert.equal(packageJson.scripts['supabase:apply-policies'], 'node scripts/apply-supabase-policies.js')
  assert.match(applyPoliciesScript, /APPLY_SUPABASE_POLICIES/)
  assert.match(applyPoliciesScript, /SUPABASE_DB_URL/)
  assert.match(applyPoliciesScript, /VITE_SUPABASE_URL/)
  assert.match(applyPoliciesScript, /EXPECTED_SUPABASE_URL/)
  assert.match(applyPoliciesScript, /EVENT_ADMIN_USERNAME/)
  assert.match(applyPoliciesScript, /EVENT_ADMIN_PASSWORD/)
  assert.match(applyPoliciesScript, /--from requires an env file path\./)
  assert.match(applyPoliciesScript, /--allow-local-db/)
  assert.match(applyPoliciesScript, /isLocalDatabaseHost/)
  assert.match(applyPoliciesScript, /Refusing to apply event policies to a local Postgres host/)
  assert.match(applyPoliciesScript, /getSupabaseProjectRef/)
  assert.match(applyPoliciesScript, /does not match VITE_SUPABASE_URL or EXPECTED_SUPABASE_URL/)
  assert.match(applyPoliciesScript, /must be a real Supabase project URL when provided/)
  assert.match(applyPoliciesScript, /parseEnvFile/)
  assert.match(applyPoliciesScript, /redactCliOutput/)
  assert.match(applyPoliciesScript, /const redactApplyOutput = \(value\) =>/)
  assert.match(applyPoliciesScript, /const buildPsqlEnv = \(connectionUrl\) =>/)
  assert.match(applyPoliciesScript, /Object\.fromEntries\(Object\.entries\(/)
  assert.match(applyPoliciesScript, /\.filter\(\(\[, value\]\) => value !== undefined\)/)
  assert.match(applyPoliciesScript, /PGHOST: parsed\.hostname/)
  assert.match(applyPoliciesScript, /PGPASSWORD: decodeURIComponent\(parsed\.password\)/)
  assert.match(applyPoliciesScript, /PGDATABASE: database/)
  assert.match(applyPoliciesScript, /PGSSLMODE: sslMode/)
  assert.match(applyPoliciesScript, /env: buildPsqlEnv\(dbUrl\)/)
  assert.doesNotMatch(applyPoliciesScript, /run\('psql', \[\s*dbUrl/)
  assert.match(applyPoliciesScript, /adminPassword/)
  assert.match(applyPoliciesScript, /replaceAll\(secret, '<redacted>'\)/)
  assert.match(applyPoliciesScript, /postgres\(\?:ql\)\?:\\\/\\\/\[\^\\s'"\]\+/)
  assert.doesNotMatch(applyPoliciesScript, /console\.error\(result\.stderr \|\| result\.stdout\)/)
  assert.match(applyPoliciesScript, /options\.apply/)
  assert.match(applyPoliciesScript, /change-this-password/)
  assert.match(applyPoliciesScript, /replace-with-strong-event-password/)
  assert.match(applyPoliciesScript, /iamadmin/)
  assert.match(applyPoliciesScript, /must not be a placeholder or known weak value/)
  assert.match(applyPoliciesScript, /project-ref\|example\|region/)
  assert.match(applyPoliciesScript, /server\/supabase_policies\.sql/)
  assert.match(applyPoliciesScript, /admin_credential_configured/)
  assert.match(applyPoliciesScript, /login_admin_session/)
  assert.match(applyPoliciesScript, /admin credential row is visible to anon/)
  assert.match(applyPoliciesScript, /select password from public\.teams/)
  assert.match(applyPoliciesScript, /post-apply checks passed/)
})

test('manual event workflow runs the live Supabase mutation gate with secrets', () => {
  const workflow = readProjectFile('.github/workflows/verify-event.yml')
  const productionDeployWorkflow = readProjectFile('.github/workflows/verify-production-deploy.yml')
  const verifyWorkflow = readProjectFile('.github/workflows/verify.yml')
  const packageJson = JSON.parse(readProjectFile('package.json'))
  const vercelBuildEnv = readProjectFile('scripts/verify-vercel-build-env.js')
  const verifyVercelProductionEnv = readProjectFile('scripts/verify-vercel-production-env.js')
  const vercelEnvUtils = readProjectFile('scripts/vercel-env-utils.js')
  const withVercelEnv = readProjectFile('scripts/with-vercel-production-env.js')
  const setVercelProductionEnv = readProjectFile('scripts/set-vercel-production-env.js')
  const renderSupabaseEventSql = readProjectFile('scripts/render-supabase-event-sql.js')
  const deployProduction = readProjectFile('scripts/deploy-production.js')
  const productionDeployVerifier = readProjectFile('scripts/verify-production-deploy.js')
  const browserSmoke = readProjectFile('scripts/verify-browser-smoke.js')
  const configuredBrowserSmoke = readProjectFile('scripts/verify-configured-browser-smoke.js')
  const releaseVerifier = readProjectFile('scripts/verify-release.js')
  const liveStatusVerifier = readProjectFile('scripts/verify-live-status.js')
  const readme = readProjectFile('README.md')
  const productionEnvExample = readProjectFile('.env.production.local.example')

  assert.match(workflow, /workflow_dispatch:/)
  assert.match(workflow, /VITE_SUPABASE_URL: \$\{\{ secrets\.VITE_SUPABASE_URL \}\}/)
  assert.match(workflow, /VITE_SUPABASE_ANON_KEY: \$\{\{ secrets\.VITE_SUPABASE_ANON_KEY \}\}/)
  assert.match(workflow, /VERIFY_SUPABASE_MUTATIONS: "1"/)
  assert.match(workflow, /VERIFY_SUPABASE_ADMIN_USERNAME: \$\{\{ secrets\.VERIFY_SUPABASE_ADMIN_USERNAME \}\}/)
  assert.match(workflow, /VERIFY_SUPABASE_ADMIN_PASSWORD: \$\{\{ secrets\.VERIFY_SUPABASE_ADMIN_PASSWORD \}\}/)
  assert.match(workflow, /node-version: 24/)
  assert.match(workflow, /npm exec --yes playwright -- install --with-deps chromium/)
  assert.match(workflow, /run: npm run verify:event/)
  assert.match(productionDeployWorkflow, /workflow_dispatch:/)
  assert.match(productionDeployWorkflow, /production_url:/)
  assert.match(productionDeployWorkflow, /default: https:\/\/tech-token-heist-one\.vercel\.app/)
  assert.match(productionDeployWorkflow, /expected_supabase_url:/)
  assert.match(productionDeployWorkflow, /PRODUCTION_URL: \$\{\{ inputs\.production_url \}\}/)
  assert.match(productionDeployWorkflow, /EXPECTED_SUPABASE_URL: \$\{\{ inputs\.expected_supabase_url \}\}/)
  assert.match(productionDeployWorkflow, /run: npm run verify:production-deploy/)
  assert.match(verifyWorkflow, /run: npm run verify:supabase:local-sql/)
  assert.match(verifyWorkflow, /node-version: \[22, 24\]/)
  assert.match(verifyWorkflow, /npm exec --yes playwright -- install --with-deps chromium/)
  assert.match(verifyWorkflow, /run: npm run verify:browser/)
  assert.match(verifyWorkflow, /run: npm run verify:browser:configured/)
  assert.match(verifyWorkflow, /run: npm run verify:admin-workflow/)
  assert.equal(packageJson.scripts.prebuild, 'node scripts/verify-vercel-build-env.js')
  assert.match(vercelBuildEnv, /process\.env\.VERCEL === '1'/)
  assert.match(vercelBuildEnv, /process\.env\.VERCEL_ENV === 'production'/)
  assert.match(vercelBuildEnv, /VITE_SUPABASE_URL/)
  assert.match(vercelBuildEnv, /VITE_SUPABASE_ANON_KEY/)
  assert.match(vercelEnvUtils, /your-project-ref/)
  assert.match(vercelEnvUtils, /your-publishable-key/)
  assert.match(vercelEnvUtils, /sb_secret_/)
  assert.match(vercelEnvUtils, /jwtPayload\.role === 'anon'/)
  assert.match(readProjectFile('src/lib/supabase.js'), /sb_secret_/)
  assert.match(readProjectFile('src/lib/supabase.js'), /jwtPayload\.role === 'anon'/)
  assert.match(vercelBuildEnv, /Blank required env vars/)
  assert.match(vercelBuildEnv, /Invalid Supabase env vars/)
  assert.match(vercelBuildEnv, /validateSupabaseProductionEnv/)
  assert.match(vercelBuildEnv, /admin_credential_configured/)
  assert.match(vercelBuildEnv, /login_team/)
  assert.match(vercelBuildEnv, /login_admin_session/)
  assert.match(vercelBuildEnv, /teams\.password is directly selectable/)
  assert.match(vercelBuildEnv, /Run server\/supabase_policies\.sql/)
  assert.match(vercelBuildEnv, /process\.exit\(1\)/)
  assert.equal(packageJson.scripts['verify:vercel-env'], 'node scripts/verify-vercel-production-env.js')
  assert.equal(packageJson.scripts['verify:production-deploy'], 'node scripts/verify-production-deploy.js')
  assert.equal(packageJson.scripts['verify:live-status'], 'node scripts/verify-live-status.js')
  assert.equal(packageJson.scripts['verify:browser:configured'], 'node scripts/verify-configured-browser-smoke.js')
  assert.equal(packageJson.scripts['verify:admin-workflow'], 'node scripts/verify-admin-workflow-smoke.js')
  assert.equal(packageJson.scripts['verify:release'], 'node scripts/verify-release.js')
  assert.equal(packageJson.scripts['deploy:production'], 'node scripts/deploy-production.js')
  assert.equal(packageJson.scripts['vercel:set-production-env'], 'node scripts/set-vercel-production-env.js')
  assert.equal(packageJson.scripts['supabase:render-event-sql'], 'node scripts/render-supabase-event-sql.js')
  assert.match(browserSmoke, /buildMissingConfigBundle/)
  assert.match(browserSmoke, /LocalNetworkAccessChecks/)
  assert.match(browserSmoke, /launchSmokeBrowser/)
  assert.match(browserSmoke, /VITE_SUPABASE_URL: ''/)
  assert.match(browserSmoke, /VITE_SUPABASE_ANON_KEY: ''/)
  assert.match(browserSmoke, /--outDir/)
  assert.match(browserSmoke, /import \{ chromium \} from 'playwright'/)
  assert.match(browserSmoke, /waitUntil: 'domcontentloaded'/)
  assert.match(browserSmoke, /data-testid=supabase-config-missing/)
  assert.match(browserSmoke, /logged console errors/)
  assert.doesNotMatch(browserSmoke, /vite\s+preview/)
  assert.match(configuredBrowserSmoke, /landing-configured/)
  assert.match(configuredBrowserSmoke, /LocalNetworkAccessChecks/)
  assert.match(configuredBrowserSmoke, /launchSmokeBrowser/)
  assert.match(configuredBrowserSmoke, /login-configured/)
  assert.match(configuredBrowserSmoke, /admin-configured/)
  assert.match(configuredBrowserSmoke, /player-configured/)
  assert.match(configuredBrowserSmoke, /arena-configured/)
  assert.match(configuredBrowserSmoke, /battle-configured/)
  assert.match(configuredBrowserSmoke, /rulebook-configured/)
  assert.match(configuredBrowserSmoke, /about-configured/)
  assert.match(configuredBrowserSmoke, /devs-configured/)
  assert.match(configuredBrowserSmoke, /createReadOnlySupabaseRouteHandler/)
  assert.match(configuredBrowserSmoke, /page\.route/)
  assert.match(configuredBrowserSmoke, /pageerror/)
  assert.match(configuredBrowserSmoke, /logged console errors/)
  assert.match(productionDeployVerifier, /event-hardening-2026-05-16/)
  assert.match(productionDeployVerifier, /FETCH_TIMEOUT_MS = 15_000/)
  assert.match(productionDeployVerifier, /AbortSignal\.timeout\(FETCH_TIMEOUT_MS\)/)
  assert.match(productionDeployVerifier, /return \{ ok: true, response, text, url \}/)
  assert.match(productionDeployVerifier, /return \{[\s\S]*ok: false,[\s\S]*error,[\s\S]*text: '',[\s\S]*url,[\s\S]*\}/)
  assert.match(productionDeployVerifier, /could not be fetched from production/)
  assert.match(productionDeployVerifier, /Production JavaScript bundle could not be fetched/)
  assert.match(productionDeployVerifier, /Production bundle does not contain a concrete Supabase project URL/)
  assert.match(productionDeployVerifier, /EXPECTED_SUPABASE_URL/)
  assert.match(productionDeployVerifier, /VITE_SUPABASE_URL/)
  assert.match(productionDeployVerifier, /rawExpectedSupabaseUrl/)
  assert.match(productionDeployVerifier, /EXPECTED_SUPABASE_URL or VITE_SUPABASE_URL is not a valid URL/)
  assert.match(productionDeployVerifier, /content-security-policy/)
  assert.match(productionDeployVerifier, /referrer-policy/)
  assert.match(productionDeployVerifier, /permissions-policy/)
  assert.match(productionDeployVerifier, /Supabase realtime connect-src/)
  assert.match(productionDeployVerifier, /object-src 'none'/)
  assert.match(productionDeployVerifier, /frame-ancestors 'none'/)
  assert.match(productionDeployVerifier, /immutable one-year asset caching/)
  assert.match(productionDeployVerifier, /PRODUCTION_ENTRYPOINTS/)
  assert.match(productionDeployVerifier, /'\/admin'/)
  assert.match(productionDeployVerifier, /'\/admin\.html'/)
  assert.match(productionDeployVerifier, /'\/login'/)
  assert.match(productionDeployVerifier, /'\/login\.html'/)
  assert.match(productionDeployVerifier, /HTML entrypoints checked/)
  assert.match(productionDeployVerifier, /Supabase connect-src/)
  assert.match(productionDeployVerifier, /findLeakedSupabaseClientSecrets/)
  assert.match(productionDeployVerifier, /sb_secret_/)
  assert.match(productionDeployVerifier, /service_role/)
  assert.match(productionDeployVerifier, /parseJwtPayload/)
  assert.match(releaseVerifier, /--require-supabase-admin/)
  assert.match(withVercelEnv, /EXPECTED_SUPABASE_URL/)
  assert.match(withVercelEnv, /VITE_SUPABASE_URL/)
  assert.match(withVercelEnv, /validateSupabaseProductionEnv/)
  assert.match(withVercelEnv, /validateAdminVerifierEnv/)
  assert.match(withVercelEnv, /Missing required admin verification vars/)
  assert.match(withVercelEnv, /Invalid admin verification vars/)
  assert.match(withVercelEnv, /formatVercelProductionEnvFix\(\)/)
  assert.match(withVercelEnv, /formatVercelProductionEnvFix/)
  assert.match(withVercelEnv, /childOutputMaxBuffer = 20 \* 1024 \* 1024/)
  assert.match(withVercelEnv, /const writeRedactedOutput = \(result\) =>/)
  assert.match(withVercelEnv, /process\.stdout\.write\(redactCliOutput\(result\.stdout\)\)/)
  assert.match(withVercelEnv, /process\.stderr\.write\(redactCliOutput\(result\.stderr\)\)/)
  assert.match(withVercelEnv, /stdio: \['inherit', 'pipe', 'pipe'\]/)
  assert.match(withVercelEnv, /maxBuffer: childOutputMaxBuffer/)
  assert.match(withVercelEnv, /writeRedactedOutput\(result\)/)
  assert.match(withVercelEnv, /const runWithVercelProductionEnv = \(\) =>/)
  assert.match(withVercelEnv, /return result\.status/)
  assert.doesNotMatch(withVercelEnv, /process\.exit\(result\.status\)/)
  assert.doesNotMatch(withVercelEnv, /stdio: 'inherit'/)
  assert.match(withVercelEnv, /result\.status === null/)
  assert.match(withVercelEnv, /Command terminated without an exit code/)
  assert.match(setVercelProductionEnv, /validateSupabaseProductionEnv/)
  assert.match(setVercelProductionEnv, /validateAdminVerifierEnv/)
  assert.match(setVercelProductionEnv, /--require-admin-verifier/)
  assert.match(setVercelProductionEnv, /--skip-supabase-health/)
  assert.match(setVercelProductionEnv, /--from requires an env file path\./)
  assert.match(setVercelProductionEnv, /options\.apply && !adminVerifier\.ok/)
  assert.match(setVercelProductionEnv, /Cannot update Vercel Production without admin verification vars/)
  assert.match(setVercelProductionEnv, /verifySupabaseProjectHealth/)
  assert.match(setVercelProductionEnv, /scratch\/test_supabase\.js/)
  assert.match(setVercelProductionEnv, /Supabase project health check failed/)
  assert.match(setVercelProductionEnv, /Skipping live Supabase health check/)
  assert.match(setVercelProductionEnv, /deploy:production still blocks on the live Supabase mutation gate/)
  assert.match(setVercelProductionEnv, /vercel'[\s\S]*'env'[\s\S]*'add'[\s\S]*'production'[\s\S]*'--force'/)
  assert.match(setVercelProductionEnv, /redactCliOutput/)
  assert.match(setVercelProductionEnv, /verifyPulledProductionEnv/)
  assert.match(setVercelProductionEnv, /verifyPulledProductionEnv\(\{ requireAdminVerifier: true \}\)/)
  assert.match(setVercelProductionEnv, /const verifyExitCode = verifyPulledProductionEnv/)
  assert.match(setVercelProductionEnv, /rmSync\(tempDir, \{ recursive: true, force: true \}\)/)
  assert.match(setVercelProductionEnv, /admin verification vars were not confirmed/)
  assert.match(setVercelProductionEnv, /Invalid admin verification vars/)
  assert.match(renderSupabaseEventSql, /event-supabase-apply\.local\.sql/)
  assert.match(renderSupabaseEventSql, /server\/supabase_policies\.sql/)
  assert.match(renderSupabaseEventSql, /validateSupabaseProductionEnv/)
  assert.match(renderSupabaseEventSql, /validateAdminVerifierEnv/)
  assert.match(renderSupabaseEventSql, /extensions\.crypt/)
  assert.match(renderSupabaseEventSql, /admin_credential_configured/)
  assert.match(renderSupabaseEventSql, /Secret values were not printed to stdout/)
  assert.match(deployProduction, /verify/)
  assert.match(deployProduction, /verify:install/)
  assert.match(deployProduction, /verify:browser/)
  assert.match(deployProduction, /verify:browser:configured/)
  assert.match(deployProduction, /verify:admin-workflow/)
  assert.match(deployProduction, /verify:supabase:local-sql/)
  assert.match(deployProduction, /verify:vercel-env/)
  assert.match(deployProduction, /vercel[\s\S]*build[\s\S]*--prod[\s\S]*--yes/)
  assert.match(deployProduction, /--require-supabase-admin/)
  assert.match(deployProduction, /verify:supabase:mutations/)
  assert.match(deployProduction, /deploy[\s\S]*--prebuilt[\s\S]*--prod[\s\S]*--yes/)
  assert.match(deployProduction, /with-vercel-production-env\.js/)
  assert.match(deployProduction, /verify:production-deploy/)
  assert.match(deployProduction, /import \{ spawn \} from 'node:child_process'/)
  assert.match(deployProduction, /createRedactedStreamWriter/)
  assert.match(deployProduction, /carryLength = 4096/)
  assert.match(deployProduction, /stdio: \['inherit', 'pipe', 'pipe'\]/)
  assert.match(deployProduction, /redactCliOutput/)
  assert.match(deployProduction, /Unknown argument/)
  assert.match(deployProduction, /--list/)
  assert.match(deployProduction, /Production deploy stopped/)
  assert.match(vercelEnvUtils, /VITE_SUPABASE_ANON_KEY/)
  assert.match(vercelEnvUtils, /REQUIRED_ADMIN_VERIFY_ENV/)
  assert.match(vercelEnvUtils, /validateAdminVerifierEnv/)
  assert.match(vercelEnvUtils, /VERIFY_SUPABASE_ADMIN_USERNAME/)
  assert.match(vercelEnvUtils, /VERIFY_SUPABASE_ADMIN_PASSWORD/)
  assert.match(vercelEnvUtils, /change-this-password/)
  assert.match(vercelEnvUtils, /replace-with-strong-event-password/)
  assert.match(vercelEnvUtils, /iamadmin/)
  assert.match(vercelEnvUtils, /Invalid required vars|invalid/)
  assert.match(vercelEnvUtils, /redactCliOutput/)
  assert.match(vercelEnvUtils, /formatVercelProductionEnvFix/)
  assert.match(verifyVercelProductionEnv, /formatVercelProductionEnvFix/)
  assert.match(verifyVercelProductionEnv, /validateAdminVerifierEnv/)
  assert.match(verifyVercelProductionEnv, /Missing required admin verification vars/)
  assert.match(verifyVercelProductionEnv, /Invalid admin verification vars/)
  assert.match(verifyVercelProductionEnv, /const verifyProductionEnv = \(\) =>/)
  assert.match(verifyVercelProductionEnv, /const exitCode = verifyProductionEnv\(\)/)
  assert.match(verifyVercelProductionEnv, /rmSync\(tempDir, \{ recursive: true, force: true \}\)/)
  assert.doesNotMatch(verifyVercelProductionEnv, /process\.exit\(pull\.status \|\| 1\)/)
  assert.match(releaseVerifier, /verify:supabase:local-sql/)
  assert.match(releaseVerifier, /verify:install/)
  assert.match(releaseVerifier, /verify:browser/)
  assert.match(releaseVerifier, /verify:browser:configured/)
  assert.match(releaseVerifier, /verify:admin-workflow/)
  assert.match(releaseVerifier, /verify:vercel-env/)
  assert.match(releaseVerifier, /with-vercel-production-env\.js/)
  assert.match(releaseVerifier, /vercel[\s\S]*build[\s\S]*--prod[\s\S]*--yes/)
  assert.match(releaseVerifier, /verify:supabase:mutations/)
  assert.doesNotMatch(releaseVerifier, /verify:production-deploy/)
  assert.match(releaseVerifier, /pre-deploy production verification gate/)
  assert.match(releaseVerifier, /deploy:production to deploy and verify the live site/)
  assert.match(releaseVerifier, /import \{ spawn \} from 'node:child_process'/)
  assert.match(releaseVerifier, /createRedactedStreamWriter/)
  assert.match(releaseVerifier, /carryLength = 4096/)
  assert.match(releaseVerifier, /stdio: \['inherit', 'pipe', 'pipe'\]/)
  assert.match(releaseVerifier, /redactCliOutput/)
  assert.match(releaseVerifier, /Unknown argument/)
  assert.match(releaseVerifier, /result\.code === null/)
  assert.match(releaseVerifier, /terminated without an exit code/)
  assert.match(releaseVerifier, /--list/)
  assert.match(liveStatusVerifier, /verify:vercel-env/)
  assert.match(liveStatusVerifier, /verify:supabase/)
  assert.match(liveStatusVerifier, /verify:production-deploy/)
  assert.match(liveStatusVerifier, /EXPECTED_SUPABASE_URL/)
  assert.match(liveStatusVerifier, /parseEnvFile/)
  assert.match(liveStatusVerifier, /validateSupabaseProductionEnv/)
  assert.match(liveStatusVerifier, /tth-vercel-live-status-/)
  assert.match(liveStatusVerifier, /vercel'[\s\S]*'env'[\s\S]*'pull'[\s\S]*'--environment=production'/)
  assert.match(liveStatusVerifier, /buildEnv: buildLiveDeploymentEnv/)
  assert.match(liveStatusVerifier, /const env = check\.buildEnv \? check\.buildEnv\(\) : process\.env/)
  assert.match(liveStatusVerifier, /env,\s*shell: isWindows/)
  assert.match(liveStatusVerifier, /const writeChildOutput = \(result\) =>/)
  assert.match(liveStatusVerifier, /process\.stderr\.write\(redactCliOutput\(result\.stderr\)\)/)
  assert.doesNotMatch(liveStatusVerifier, /process\.stdout\.write\(redactCliOutput\(result\.stderr\)\)/)
  assert.match(liveStatusVerifier, /redactCliOutput/)
  assert.match(liveStatusVerifier, /const failures = \[\]/)
  assert.match(liveStatusVerifier, /for \(const check of checks\)/)
  assert.match(liveStatusVerifier, /failures\.push/)
  assert.match(liveStatusVerifier, /Live event status: NOT READY/)
  assert.match(liveStatusVerifier, /This does not build, deploy, or write Vercel\/Supabase state/)
  assert.match(readme, /deploy:production[\s\S]*lockfile install gate[\s\S]*local browser smoke[\s\S]*configured browser smoke/)
  assert.match(readme, /deploy:production[\s\S]*live Supabase mutation gate[\s\S]*live production deployment verifier/)
  assert.match(readme, /verify:live-status[\s\S]*Vercel Production env verifier[\s\S]*read-only Supabase schema\/RLS[\s\S]*verifier[\s\S]*public production deploy[\s\S]*same Supabase project/)
  assert.match(readme, /supabase:apply-policies -- --from \.env\.production\.local --apply/)
  assert.match(readme, /supabase:render-event-sql -- --from \.env\.production\.local/)
  assert.match(readme, /event-supabase-apply\.local\.sql/)
  assert.match(readme, /contains the event admin password/)
  assert.match(readme, /--skip-supabase-health/)
  assert.match(readme, /deploy:production[\s\S]*live Supabase mutation/)
  assert.match(productionEnvExample, /SUPABASE_DB_URL=/)
  assert.match(productionEnvExample, /EVENT_ADMIN_USERNAME=admin-professor/)
  assert.match(productionEnvExample, /VERIFY_SUPABASE_ADMIN_PASSWORD=/)
})

test('HTML entrypoints carry the event deployment marker', () => {
  const marker = 'event-hardening-2026-05-16'
  const htmlEntrypoints = [
    'index.html',
    'login.html',
    'lobby.html',
    'arena.html',
    'battle.html',
    'rulebook.html',
    'about.html',
    'devs.html',
    'admin.html',
  ]

  for (const entrypoint of htmlEntrypoints) {
    assert.match(
      readProjectFile(entrypoint),
      new RegExp(`<meta name="tth-event-build" content="${marker}" />`)
    )
  }
})

test('Vercel deployment headers include a restrictive CSP', () => {
  const vercelConfig = JSON.parse(readProjectFile('vercel.json'))
  const globalHeaders = vercelConfig.headers.find((entry) => entry.source === '/(.*)')?.headers || []
  const headerByKey = new Map(globalHeaders.map((header) => [header.key.toLowerCase(), header.value]))
  const csp = headerByKey.get('content-security-policy') || ''
  assert.equal(headerByKey.get('x-content-type-options'), 'nosniff')
  assert.equal(headerByKey.get('x-frame-options'), 'DENY')
  assert.match(csp, /default-src 'self'/)
  assert.match(csp, /script-src 'self'/)
  assert.match(csp, /style-src 'self' 'unsafe-inline'/)
  assert.doesNotMatch(csp, /fonts\.googleapis\.com|fonts\.gstatic\.com/)
  assert.match(csp, /font-src 'self' data:/)
  assert.match(csp, /connect-src 'self' https:\/\/\*\.supabase\.co wss:\/\/\*\.supabase\.co/)
  assert.match(csp, /object-src 'none'/)
  assert.match(csp, /frame-ancestors 'none'/)
})

test('shipped app does not depend on external font stylesheets', () => {
  const shippedTextFiles = [
    'index.html',
    'login.html',
    'lobby.html',
    'arena.html',
    'battle.html',
    'rulebook.html',
    'about.html',
    'devs.html',
    'admin.html',
    'src/index.css',
    'src/PlayerLayout.css',
    'src/screens/AdminScreen.css',
    'src/screens/LoginScreen.css',
    'src/screens/LandingScreen.css',
    'tailwind.config.js',
    'vercel.json',
  ]

  const shippedText = shippedTextFiles.map((file) => readProjectFile(file)).join('\n')

  assert.doesNotMatch(shippedText, /fonts\.googleapis\.com|fonts\.gstatic\.com/)
  assert.doesNotMatch(shippedText, /@import\s+url\(['"]?https?:\/\//)
  assert.doesNotMatch(shippedText, /rel=["']preconnect["'][^>]+https?:\/\//)
})
